"""added user_email to user model for database table

Revision ID: 319bc93b47c8
Revises: 
Create Date: 2017-11-25 04:01:07.023000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319bc93b47c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_email', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'users', ['user_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_email')
    # ### end Alembic commands ###
